language: generic

addons:
  ssh_known_hosts: bcc.ime.usp.br

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script:
    - ssh -oBatchMode=yes encontro-deploy@bcc.ime.usp.br /opt/semanadacomputacao/script.sh
  on:
    branch: master
